In [14]:
import pandas as pd
df= pd.read_csv("ecommerce_sales_analytics_5000.csv", parse_dates=['order_date'])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[ns]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(4), object(3)
memory usage: 468.9+ KB

In [20]:
df['Payment_Type'] = df['payment_method'].map({
    'Card': 'Digital',
    'Wallet': 'Digital',
    'COD': 'Cash'
}).fillna('Other')

In [21]:
df['Payment_Type'].unique()

array(['Digital', 'Cash'], dtype=object)

In [22]:
df[['Payment_Type','payment_method']].head()

  Payment_Type payment_method
0      Digital         Wallet
1      Digital           Card
2         Cash            COD
3      Digital         Wallet
4      Digital         Wallet

In [24]:
df.groupby("Payment_Type").size()

Payment_Type
Cash       1774
Digital    3226
dtype: int64

In [25]:
def revenue_category(row):
    if row["revenue"] > 500:
        return "High"
    elif row["revenue"] >= 200:
        return "Medium"
    else:
        return "Low"

df["revenue_category"] = df.apply(revenue_category, axis=1)

In [26]:
df["revenue_category"].value_counts()

revenue_category
High      3252
Medium    1098
Low        650
Name: count, dtype: int64

In [29]:
# Select the 10 samples first, then sort them
sample_df = df[["revenue", "revenue_category"]].sample(10)

# Define the custom order
order = {"High": 0, "Medium": 1, "Low": 2}

# Sort based on the mapping
sorted_sample = sample_df.sort_values(
    by="revenue_category", 
    key=lambda x: x.map(order)
)

print(sorted_sample)

      revenue revenue_category
2487  2381.66             High
3231   734.18             High
4839  1299.59             High
161   2975.46             High
4313  2118.14             High
3224   742.40             High
1220   296.47           Medium
2034   206.51           Medium
3775   425.26           Medium
1214   200.99           Medium

In [33]:
def add_profit(data):
    data["profit"] = data["revenue"] * 0.20
    return data

df = ( 
    df
    .pipe(add_profit)
)

In [34]:
df[['revenue', 'profit']].head()

   revenue   profit
0  1883.20  376.640
1   304.10   60.820
2   644.35  128.870
3  2569.90  513.980
4   468.56   93.712